### PR TITLE
Added ability to "lock" quests

### PR DESCRIPTION
**Pull request by Wupin**
I have reworked [this PR](https://github.com/AuroraNetworkStudios/AuroraQuests/pull/2). I added the method `Quest#tryStart(Player, boolean)` so that I can detect whether the method was called by a command. Additionally, I modified the command completion for `@pools` so that it no longer adds 'none' and 'all'. Instead, I added them separately into CommandCompletion.

### CODE REVIEW

**Comment by ErikSzabo** [comment]
So, I renamed the config option and improved the command completion to narrow down quest ids based on the given pool. I also tweaked the logic how the command unlocks a quest. This way it looks nicer and possibly usable for timed-random quests as well. Please review the changes.
**NOTE** I still haven't tested this code yet.

**Comment by Wupin** [comment]
I've fixed the command completion for `@quests`, but I still need to figure out why error messages are printed when completing an invalid pool, instead of after entering the command.

**Comment by Wupin** [comment]
Fixed command completion, I removed the QuestPool context, which was printing message errors during completion. Now everything is fixed and working. Feel free to test it even more.

**Comment by ErikSzabo** [comment]
The main thing I will test is that the previous quest start/unlock behaviours are still working as expected as well as the automatic unlock listeners. Otherwise the PR looks good. I need a few days though since I just came back from the hospital. Thank you!

**Comment by ErikSzabo** [comment]
Looks fine, thanks!

**Pull request merged**
